#!/bin/zsh

# test wrong inputs
#	dev / null, dev / random, etc > print error msg

INDEX=1
declare -a WRONG_INPUTS=("/dev/null" "/dev/random" "/dev/zero")
for i in $WRONG_INPUTS; do
	ERROR_MSG=""
	SUCCESS=0
	RETURN=`$ASM_NEW $i | cut -d ' ' -f -1`
	if [ $RETURN = "Syntax" ]; then
		SUCCESS=1
	else
		SUCCESS=0
		ERROR_MSG="the asm didn't detect an error"
	fi
	print_result $INDEX $i $SUCCESS $ERROR_MSG
	let "INDEX+=1"
done
