#!/bin/zsh

ERROR_MSG=""
SUCCESS=0
declare -l FILENAME="inputs/01.s"
$ASM_ORIGINAL $FILENAME $FILENAME > /dev/null
BTCODE_NAME=`echo $FILENAME | cut -d / -f 2 | cut -d . -f 1`
COR_FILE="inputs/$BTCODE_NAME.cor"
COR_ORIGINAL="tmp/$BTCODE_NAME.cor"
mv $COR_FILE $COR_ORIGINAL
$ASM_NEW $FILENAME $FILENAME > /dev/null
COR_NEW=`echo $FILENAME | cut -d . -f 1`".cor"
if [ -e $COR_NEW ]; then
	DIFF=`diff $COR_NEW $COR_ORIGINAL`
	if [ "$DIFF" != "" ]; then
		SUCCESS=0
		ERROR_MSG="diff delta between the .cor files"
	else
		SUCCESS=1
	fi
else
	SUCCESS=0
	ERROR_MSG=""
fi
print_result 1 "no arg" $SUCCESS $ERROR_MSG
