# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abaurens <abaurens@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 16:08:06 by abaurens          #+#    #+#              #
#    Updated: 2019/09/09 16:43:46 by abaurens         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LINKER	:=	gcc -r -nostdlib -o
NAME	:=	ftlib

# SOURCES

SRC		:=	\
			ft_match.c				\
			ft_idxof.c				\
			ft_bzero.c				\
			ft_split.c				\
			ft_strequ.c				\
			ft_strlen.c				\
			ft_strmap.c				\
			ft_strnew.c				\
			ft_isbase.c				\
			ft_memchr.c				\
			ft_memcmp.c				\
			ft_memcpy.c				\
			ft_memdel.c				\
			ft_memset.c				\
			ft_numlen.c				\
			ft_strcat.c				\
			ft_strchr.c				\
			ft_strclr.c				\
			ft_strcmp.c				\
			ft_strcpy.c				\
			ft_strdel.c				\
			ft_strdup.c				\
			ft_strstr.c				\
			ft_strsub.c				\
			ft_strndup.c			\
			ft_isspace.c			\
			ft_strncat.c			\
			ft_isupper.c			\
			ft_strncmp.c			\
			ft_freturn.c			\
			ft_strnstr.c			\
			ft_strrchr.c			\
			ft_strmapi.c			\
			ft_strmcat.c			\
			ft_memmove.c			\
			ft_strncpy.c			\
			ft_strnequ.c			\
			ft_striter.c			\
			ft_strjoin.c			\
			ft_strlcat.c			\
			ft_strtrim.c			\
			ft_tolower.c			\
			ft_toupper.c			\
			ft_isdigit.c			\
			ft_islower.c			\
			ft_isprint.c			\
			ft_isalnum.c			\
			ft_isalpha.c			\
			ft_isascii.c			\
			ft_memccpy.c			\
			ft_isnumber.c			\
			ft_striteri.c			\
			ft_strsplit.c			\
			ft_contains.c			\
			ft_memalloc.c			\
			ft_strupcase.c			\
			ft_count_words.c		\
			ft_unsignedlen.c		\
			ft_isnumber_base.c		\
			ft_unsignedlen_base.c

include variables.mk
override CFLAGS	+=	-ansi -pedantic
include rules.mk
